# config/components/selectors.yaml - Input component configurations
selectors:
  types:
    radio:
      template: "radio_buttons"
      defaultClass: "radio-group"
    select:
      template: "select_input"
      defaultClass: "select-group"
    checkbox:
      template: "checkbox_group"
      defaultClass: "checkbox-group"
    compound:
      template: "compound_input"
      defaultClass: "compound-group"
    date_range:
      template: "date_range"
      defaultClass: "date-range"

  shared:
    location:
      type: "select"
      label: "Select Location:"
      popover:
        title: "Which Location to Analyze?"
        content: "Select the metropolitan area for analysis."
      options:
        none:
          id: "none"
          label: "None"
        atlanta:
          id: "C.12580"
          label: "Atlanta-Sandy Springs-Roswell, GA"
        miami:
          id: "C.33100"
          label: "Miami-Fort Lauderdale-Pompano Beach, FL"
        chicago:
          id: "C.16980"
          label: "Chicago-Naperville-Elgin, IL-IN-WI"
        
        