selectors:
  location:
    inherit: "prerun.location"
    ui:
      type: "select"
      label: "Location"
      
  subgroups:
    ui:
      type: "numeric"
      label: "How Many Distinct Subgroups to Target Interventions To:"
      min: 1
      max: 5
      value: 1

  # Demographics for each subgroup
  age_groups:
    options:
      all:
        id: "all"
        label: "Include All Age Groups"
      13-24:
        id: "13-24"
        label: "13-24 years"
      25-34:
        id: "25-34"
        label: "25-34 years"
      35-44:
        id: "35-44"
        label: "35-44 years"
      45-54:
        id: "45-54"
        label: "45-54 years"
      55plus:
        id: "55plus"
        label: "55+ years"
    ui:
      type: "checkbox"
      label: "Age Group"

  race_ethnicity:
    options:
      all:
        id: "all"
        label: "Include All Races"
      black:
        id: "black"
        label: "Black"
      hispanic:
        id: "hispanic"
        label: "Hispanic"
      other:
        id: "other"
        label: "Other"
    ui:
      type: "checkbox"
      label: "Race/Ethnicity"

  biological_sex:
    options:
      all:
        id: "all"
        label: "Include All Sexes"
      male:
        id: "male"
        label: "Male"
      female:
        id: "female"
        label: "Female"
    ui:
      type: "checkbox"
      label: "Biological Sex"

  risk_factor:
    options:
      all:
        id: "all"
        label: "Include All Risk Factors"
      msm:
        id: "msm"
        label: "MSM"
      active_idu:
        id: "active_idu"
        label: "Active IDU"
      prior_idu:
        id: "prior_idu"
        label: "Prior IDU"
      msm_active_idu:
        id: "msm_active_idu"
        label: "MSM + Active IDU"
      msm_prior_idu:
        id: "msm_prior_idu"
        label: "MSM + Prior IDU"
      heterosexual:
        id: "heterosexual"
        label: "Heterosexual"
    ui:
      type: "checkbox"
      label: "Risk Factor"

  # Intervention components
  intervention_dates:
    ui:
      type: "date_range"
      label: "Intervention Roll-Out:"
      start:
        label: "Begins in:"
        options:
          from: 2023
          to: 2030
          format: "%Y (%b 1)"  # e.g., "2023 (Jan 1)"
      end:
        label: "Fully Implemented by:"
        options:
          from: 2023
          to: 2030
          format: "%Y (%b 31)"  # e.g., "2027 (Dec 31)"

  testing:
    ui:
      type: "compound"
      label: "Intervene on Testing"
      inputs:
        enabled:
          type: "checkbox"
          label: "Intervene on Testing"
        frequency:
          type: "select"
          label: "Average number of tests per person:"
          options:
            once: "Once per year"
            twice: "Twice per year"
            four: "Four times per year"

  prep:
    ui:
      type: "compound"
      label: "Intervene on PrEP"
      inputs:
        enabled:
          type: "checkbox"
          label: "Intervene on PrEP"
        coverage:
          type: "numeric"
          label: "PrEP Coverage:"
          min: 0
          max: 100
          step: 5
          value: 10
          format: "percentage"

  suppression:
    ui:
      type: "compound"
      label: "Intervene on Suppression"
      inputs:
        enabled:
          type: "checkbox"
          label: "Intervene on Suppression"
        proportion:
          type: "numeric"
          label: "Proportion of diagnosed PWH who are Suppressed:"
          min: 0
          max: 100
          step: 5
          value: 70
          format: "percentage"

  needle_exchange:
    ui:
      type: "compound"
      label: "Intervene on Needle Exchange"
      inputs:
        enabled:
          type: "checkbox"
          label: "Intervene on Needle Exchange"
        proportion:
          type: "numeric"
          label: "Proportion of PWID in Needle Exchange Programs:"
          min: 0
          max: 100
          step: 5
          value: 10
          format: "percentage"

  moud:
    ui:
      type: "compound"
      label: "Intervene on MOUDs"
      inputs:
        enabled:
          type: "checkbox"
          label: "Intervene on MOUDs"
        proportion:
          type: "numeric"
          label: "Proportion of PWID on MOUDs:"
          min: 0
          max: 100
          step: 5
          value: 10
          format: "percentage"

# Plot controls matching screenshot
plot_controls:
  outcomes:
    options:
      incidence:
        id: "incidence"
        label: "Incidence"
      diagnoses:
        id: "diagnoses"
        label: "Reported Diagnoses"
      prevalence:
        id: "prevalence"
        label: "Prevalence (Diagnosed)"
      mortality:
        id: "mortality"
        label: "HIV Mortality"
      testing:
        id: "testing"
        label: "HIV Testing Rates"
      prep:
        id: "prep"
        label: "PrEP Coverage"
      suppression:
        id: "suppression"
        label: "Viral Suppression"
      knowledge:
        id: "knowledge"
        label: "Knowledge of Status"
    ui:
      type: "checkbox"
      label: "Outcomes"

  projection_options:
    stratification:
      options:
        age_group:
          id: "age"
          label: "Age Group"
        race_ethnicity:
          id: "race"
          label: "Race/Ethnicity"
        biological_sex:
          id: "sex"
          label: "Biological Sex"
        risk_factor:
          id: "risk"
          label: "Risk Factor"
      ui:
        type: "checkbox"
        label: "Separate Projections By:"

    summary:
      ui:
        type: "compound"
        label: "Summarize the Outcomes As:"
        inputs:
          type:
            type: "select"
            label: null
            options:
              change: "Change Over Time"
              absolute: "Raw Values"
          time_range:
            type: "compound"
            inputs:
              from:
                type: "select"
                label: "from:"
                options:
                  from: 2020
                  to: 2030
              to:
                type: "select"
                label: "to:"
                options:
                  from: 2020
                  to: 2030
          show_change:
            type: "checkbox"
            label: "Label this change on the figure"

    display:
      ui:
        type: "radio"
        label: "What to Show for Projections:"
        options:
          mean:
            id: "mean"
            label: "The Mean Estimate and 95% Credible Interval"
          individual:
            id: "individual"
            label: "Each Individual Simulation"