selectors:
  location:
    options:
      none:
        id: "none"
        label: "None"
      atlanta:
        id: "C.12580"
        label: "Atlanta-Sandy Springs-Roswell, GA"
      miami:
        id: "C.33100"
        label: "Miami-Fort Lauderdale-Pompano Beach, FL"
      chicago:
        id: "C.16980"
        label: "Chicago-Naperville-Elgin, IL-IN-WI"
      detroit:
        id: "C.19820"
        label: "Detroit-Warren-Dearborn, MI"
      houston:
        id: "C.26420"
        label: "Houston-The Woodlands-Sugar Land, TX"
      losangeles:
        id: "C.31080"
        label: "Los Angeles-Long Beach-Anaheim, CA"
      newyork:
        id: "C.35620"
        label: "New York-Newark-Jersey City, NY-NJ-PA"
      philadelphia:
        id: "C.37980"
        label: "Philadelphia-Camden-Wilmington, PA-NJ-DE-MD"
      phoenix:
        id: "C.38060"
        label: "Phoenix-Mesa-Chandler, AZ"
      seattle:
        id: "C.42660"
        label: "Seattle-Tacoma-Bellevue, WA"
      washingtondc:
        id: "C.47900"
        label: "Washington-Arlington-Alexandria, DC-VA-MD-WV"
    ui:
      type: "select"
      label: "Select Location:"
      popover:
        title: "Which Location to Analyze?"
        content: "Select the metropolitan area for analysis."

  intervention_aspects:
    options:
      none:
        id: "none"
        label: "None"
      testing:
        id: "hivtesting"
        label: "HIV Testing"
      prep:
        id: "prep"
        label: "PrEP Coverage"
      viral:
        id: "viralsuppression"
        label: "Viral Suppression"
      exchange:
        id: "needleexchange"
        label: "Needle Exchange"
      moud:
        id: "moud"
        label: "MOUDs"
    ui:
      type: "radio"
      label: "Which Aspects to Intervene On:"
      popover:
        title: "What Should the Intervention Affect?"
        content: "You can choose interventions that affect HIV testing, PrEP among those at risk for HIV acquisition, viral suppression among PWH, participation in needle-exchange programs, MOUDs (medications for opioid use disorder), or combinations of these"

  population_groups:
    options:
      all:
        id: "all"
        label: "All populations"
      age:
        id: "age_groups"
        label: "By age groups:<br/>13-24, 25-34, 35-44, 45-54, 55+"
      risk:
        id: "risk_groups"
        label: "By risk groups:<br/>MSM, IDU, heterosexual contact"
    ui:
      type: "radio"
      label: "Target Population:"
      popover:
        title: "Which Groups to Target?"
        content: "Select whether to apply interventions across all populations or target specific demographic or risk groups."

  timeframes:
    options:
      immediate:
        id: "2024_2025"
        label: "2024-2025 (Immediate)"
      short:
        id: "2024_2026"
        label: "2024-2026 (Short-term)"
      medium:
        id: "2024_2028"
        label: "2024-2028 (Medium-term)"
      long:
        id: "2024_2030"
        label: "2024-2030 (Long-term)"
    ui:
      type: "radio"
      label: "Intervention Roll-Out Period:"
      popover:
        title: "When to Roll Out the Intervention?"
        content: "Select the time period over which the intervention will be implemented. Longer periods allow for more gradual implementation."

  intensities:
    options:
      moderate:
        id: "moderate"
        label: "Moderate increase in coverage"
      substantial:
        id: "substantial"
        label: "Substantial increase in coverage"
      aggressive:
        id: "aggressive"
        label: "Aggressive increase in coverage"
      maximum:
        id: "maximum"
        label: "Maximum feasible coverage"
    ui:
      type: "radio"
      label: "Intervention Intensity:"
      popover:
        title: "How Intensive Should the Intervention Be?"
        content: "Select the level of coverage increase to model. More aggressive increases require more resources but may have larger impacts."