# Contact page configuration
page:
  title: "Contact Us"
  subtitle: "Get in Touch with the JHEEM Team"
  description: "We welcome any feedback, comments, questions, or requests"

form:
  fields:
    name:
      label: "Your name"
      type: "text"
      placeholder: "Enter your name"
      required: true
    
    email:
      label: "Your email"
      type: "email"
      placeholder: "Enter your email address"
      required: true
    
    message:
      label: "Your message"
      type: "textarea"
      placeholder: "Your feedback, comments, questions, or requests"
      required: true
      rows: 10

  submit:
    label: "Submit"
    class: "btn btn-primary"

layout:
  container:
    class: "contact-container"
  form:
    class: "contact-form"
    width: "500px"
    margin: "0 auto" 