# config/pages/custom.yaml - Custom page specific settings
# Simplified version for ryan-white branch

# Intervention configuration
interventions:
  # Keep the date range selector
  dates:
    type: "date_range"
    start:
      type: "select"
      input_style: "choices"
      multiple: false
      label: "Begins in:"
      placeholder: "Select start year..."
      min: 2023
      max: 2030
      value: 2023
      options:
        2023:
          id: "2023"
          label: "2023"
        2024:
          id: "2024"
          label: "2024"
        2025:
          id: "2025"
          label: "2025"
        2026:
          id: "2026"
          label: "2026"
        2027:
          id: "2027"
          label: "2027"
        2028:
          id: "2028"
          label: "2028"
        2029:
          id: "2029"
          label: "2029"
        2030:
          id: "2030"
          label: "2030"
    end:
      type: "select"
      input_style: "choices"
      multiple: false
      label: "Fully Implemented by:"
      placeholder: "Select end year..."
      min: 2023
      max: 2030
      value: 2024
      options:
        2023:
          id: "2023"
          label: "2023"
        2024:
          id: "2024"
          label: "2024"
        2025:
          id: "2025"
          label: "2025"
        2026:
          id: "2026"
          label: "2026"
        2027:
          id: "2027"
          label: "2027"
        2028:
          id: "2028"
          label: "2028"
        2029:
          id: "2029"
          label: "2029"
        2030:
          id: "2030"
          label: "2030"

  # Simple numeric inputs for suppression loss
  components:
    suppression_loss_1:
      type: "numeric"
      label: "Category 1 Suppression Loss"
      placeholder: "Enter percentage..."
      min: 0
      max: 100
      step: 5
      value: 0
      format: "percentage"
    
    suppression_loss_2:
      type: "numeric"
      label: "Category 2 Suppression Loss"
      placeholder: "Enter percentage..."
      min: 0
      max: 100
      step: 5
      value: 0
      format: "percentage"