# src/ui/config/pages/custom.yaml - Ryan White funding impact settings

# Section configurations
sections:
  funding_timing:
    title: "Funding Change Timeline"
    description: "Specify when Ryan White funding ends and (if applicable) when it returns"
  impacts:
    title: "Client Impacts"
    description: "Define how the loss of Ryan White services would affect client viral suppression"

# Subgroups configuration - fixed for Ryan White
subgroups:
  fixed: true
  count: 3
  groups:
    - id: "adap"
      label: "ADAP Recipients"
      description: "Clients receiving any AIDS Drug Assistance Program benefits (medications, premium assistance, copay support)"
    - id: "oahs"
      label: "OAHS Recipients (without ADAP)"
      description: "Clients receiving Outpatient Ambulatory Health Services but not ADAP"
    - id: "other"
      label: "Other Services Recipients"
      description: "Clients receiving any other Ryan White services but not ADAP or OAHS"

# Intervention configuration
interventions:
  # Implementation timing - July 1st to October 1st of selected years
  dates:
    type: "date_range"
    start:
      type: "select"
      input_style: "choices"
      multiple: false
      label: "Funding Ends:"
      description: "Select the year when Ryan White funding would end"
      show_label: true
      placeholder: "Select start year..."
      min: 2025
      max: 2030
      value: 2025
      options:
        2025:
          id: "2025.5"
          label: "2025"
        2026:
          id: "2026.5"
          label: "2026"
        2027:
          id: "2027.5"
          label: "2027"
        2028:
          id: "2028.5"
          label: "2028"
        2029:
          id: "2029.5"
          label: "2029"
        2030:
          id: "2030.5"
          label: "2030"
    end:
      type: "select"
      input_style: "choices"
      multiple: false
      label: "Funding Returns:"
      description: "Select when (or if) funding would be restored"
      show_label: true
      placeholder: "Select return year (if applicable)..."
      min: 2025
      max: 2035
      value: 2025
      options:
        never:
          id: "never"
          label: "Never Returns"
        2026:
          id: "2026.5"
          label: "2026"
        2027:
          id: "2027.5"
          label: "2027"
        2028:
          id: "2028.5"
          label: "2028"
        2029:
          id: "2029.5"
          label: "2029"
        2030:
          id: "2030.5"
          label: "2030"
        2031:
          id: "2031.5"
          label: "2031"
        2032:
          id: "2032.5"
          label: "2032"
        2033:
          id: "2033.5"
          label: "2033"
        2034:
          id: "2034.5"
          label: "2034"
        2035:
          id: "2035.5"
          label: "2035"

  # Intervention components - each group will use this same component
  components:
    suppression_loss:
      type: "numeric"
      label: "Suppression Loss"
      description: "Percentage of virally suppressed clients who would stop taking ART consistently"
      placeholder: "Enter percentage..."
      min: 0
      max: 100
      step: 1
      value: 0
      format: "percentage"

# Simulation file configuration
custom_simulations:
  provider: "onedrive"  # Options: "local", "onedrive" - change to "onedrive" to use OneDrive
  file_pattern: "base/{location}_base.Rdata"
  config_file: "src/data/providers/onedrive_resources/onedrive_sharing_links.json"  # Path to sharing links file

