# src/ui/config/pages/custom.yaml - Ryan White funding impact settings

# Subgroups configuration - fixed for Ryan White
subgroups:
  fixed: true
  count: 2
  groups:
    - id: "adap"
      label: "ADAP Recipients"
      description: "Patients receiving any ADAP benefits (full-pay medications, premium assistance, and/or copay support)"
    - id: "non_adap"
      label: "Non-ADAP Recipients"
      description: "Patients receiving Ryan White services but NO ADAP benefits"

# Intervention configuration
interventions:
  # Implementation timing - July 1st to October 1st of selected years
  dates:
    type: "date_range"
    start:
      type: "select"
      input_style: "choices"
      multiple: false
      label: "Program Changes Begin (July 1st):"
      placeholder: "Select start year..."
      min: 2025
      max: 2030
      value: 2025
      options:
        2025:
          id: "2025.5"
          label: "2025"
        2026:
          id: "2026.5"
          label: "2026"
        2027:
          id: "2027.5"
          label: "2027"
        2028:
          id: "2028.5"
          label: "2028"
        2029:
          id: "2029.5"
          label: "2029"
        2030:
          id: "2030.5"
          label: "2030"
    end:
      type: "select"
      input_style: "choices"
      multiple: false
      label: "Fully Implemented by (October 1st):"
      placeholder: "Select end year..."
      min: 2025
      max: 2030
      value: 2025
      options:
        2025:
          id: "2025.8"
          label: "2025"
        2026:
          id: "2026.8"
          label: "2026"
        2027:
          id: "2027.8"
          label: "2027"
        2028:
          id: "2028.8"
          label: "2028"
        2029:
          id: "2029.8"
          label: "2029"
        2030:
          id: "2030.8"
          label: "2030"

  # Intervention components
  components:
    suppression_loss:
      type: "numeric"
      label: "Suppression Loss"
      description: "What percentage would lose suppression if all Ryan White services stopped?"
      placeholder: "Enter percentage..."
      min: 0
      max: 100
      step: 1
      value: 0
      format: "percentage"
    testing:
      type: "compound"
      label: "Testing Rate"
      description: "Changes in testing frequency"
      inputs:
        enabled:
          type: "checkbox"
          label: "Enable testing changes"
          value: false
        value:
          type: "numeric"
          label: "New tests per year"
          min: 0
          max: 12
          step: 1
          value: 1