# config/pages/custom.yaml - Custom page specific settings

# Subgroup configuration
subgroups:
  type: "numeric"
  label: "How Many Distinct Subgroups to Target Interventions To:"
  min: 1
  max: 5
  value: 1

# Demographic selectors
demographics:
  age_groups:
    type: "select"
    input_style: "choices"
    multiple: true
    label: "Age Groups"
    placeholder: "Select age groups..."
    options:
      all:
        id: "all"
        label: "All Ages"
      "13-24":
        id: "13-24"
        label: "13-24 years"
      25-34:
        id: "25-34"
        label: "25-34 years"
      35-44:
        id: "35-44"
        label: "35-44 years"
      45-54:
        id: "45-54"
        label: "45-54 years"
      55plus:
        id: "55plus"
        label: "55+ years"

  race_ethnicity:
    type: "select"
    input_style: "choices"
    multiple: true
    label: "Race/Ethnicity"
    placeholder: "Select race/ethnicity..."
    options:
      all:
        id: "all"
        label: "Include All Races"
      black:
        id: "black"
        label: "Black"
      hispanic:
        id: "hispanic"
        label: "Hispanic"
      other:
        id: "other"
        label: "Other"

  biological_sex:
    type: "select"
    input_style: "choices"
    multiple: true
    label: "Biological Sex"
    placeholder: "Select biological sex..."
    options:
      all:
        id: "all"
        label: "Include All Sexes"
      male:
        id: "male"
        label: "Male"
      female:
        id: "female"
        label: "Female"

  risk_factor:
    type: "select"
    input_style: "choices"
    multiple: true
    label: "Risk Factor"
    placeholder: "Select risk factors..."
    options:
      all:
        id: "all"
        label: "Include All Risk Factors"
      msm:
        id: "msm"
        label: "MSM"
      active_idu:
        id: "active_idu"
        label: "Active IDU"
      prior_idu:
        id: "prior_idu"
        label: "Prior IDU"
      msm_active_idu:
        id: "msm_active_idu"
        label: "MSM + Active IDU"
      msm_prior_idu:
        id: "msm_prior_idu"
        label: "MSM + Prior IDU"
      heterosexual:
        id: "heterosexual"
        label: "Heterosexual"

# Intervention dates
interventions:
  dates:
    type: "date_range"
    start:
      type: "select"
      input_style: "choices"
      multiple: false
      label: "Begins in:"
      placeholder: "Select start year..."
      min: 2023
      max: 2030
      value: 2023
      options:
        2023:
          id: "2023"
          label: "2023"
        2024:
          id: "2024"
          label: "2024"
        2025:
          id: "2025"
          label: "2025"
        2026:
          id: "2026"
          label: "2026"
        2027:
          id: "2027"
          label: "2027"
        2028:
          id: "2028"
          label: "2028"
        2029:
          id: "2029"
          label: "2029"
        2030:
          id: "2030"
          label: "2030"
    end:
      type: "select"
      input_style: "choices"
      multiple: false
      label: "Fully Implemented by:"
      placeholder: "Select end year..."
      min: 2023
      max: 2030
      value: 2024
      options:
        2023:
          id: "2023"
          label: "2023"
        2024:
          id: "2024"
          label: "2024"
        2025:
          id: "2025"
          label: "2025"
        2026:
          id: "2026"
          label: "2026"
        2027:
          id: "2027"
          label: "2027"
        2028:
          id: "2028"
          label: "2028"
        2029:
          id: "2029"
          label: "2029"
        2030:
          id: "2030"
          label: "2030"

  components:
    testing:
      type: "compound"
      label: "Intervene on Testing"
      inputs:
        enabled:
          type: "checkbox"
          input_style: "native"
          label: "Intervene on Testing"
          value: false
        frequency:
          type: "select"
          input_style: "choices"
          multiple: false
          placeholder: "Average number of tests per person..."
          value: "once"
          options:
            once:
              id: "once"
              label: "Once per year"
            twice:
              id: "twice"
              label: "Twice per year"
            four:
              id: "four"
              label: "Four times per year"

    prep:
      type: "compound"
      label: "Intervene on PrEP"
      inputs:
        enabled:
          type: "checkbox"
          input_style: "native"
          label: "Intervene on PrEP"
          value: false
        coverage:
          type: "numeric"
          placeholder: "PrEP Coverage"
          min: 0
          max: 100
          step: 5
          value: 10
          format: "percentage"

    suppression:
      type: "compound"
      label: "Intervene on Suppression"
      inputs:
        enabled:
          type: "checkbox"
          input_style: "native"
          label: "Intervene on Suppression"
          value: false
        proportion:
          type: "numeric"
          placeholder: "Proportion Suppressed"
          min: 0
          max: 100
          step: 5
          value: 70
          format: "percentage"