# config/pages/prerun.yaml - Pre-run page specific settings
# Updated for Ryan White branch

# Selector configurations
selectors:
  scenario:
    type: "select"
    input_style: "choices"
    label: "Funding Scenario"
    description: "Select whether Ryan White funding is permanently discontinued or temporarily suspended"
    show_label: false
    show_description: false
    placeholder: "Select a scenario..."
    value: "permanent_loss"  # Default to permanent loss scenario
    options:
      permanent_loss:
        id: "permanent_loss"
        label: "Permanent Funding Loss"
        description: "Ryan White funding is discontinued permanently"
      temporary_loss:
        id: "temporary_loss"
        label: "Temporary Funding Loss"
        description: "Ryan White funding is discontinued but returns in 2029"

# Simulation file configuration
prerun_simulations:
  provider: "onedrive"  # Options: "local", "onedrive" - change to "onedrive" to use OneDrive
  file_pattern: "prerun/{location}/{scenario}.Rdata"
  config_file: "src/data/providers/onedrive_resources/onedrive_sharing_links.json"  # Path to sharing links file

