# config/pages/prerun.yaml - Pre-run page specific settings
# Updated for Ryan White branch

# Selector configurations
selectors:
  scenario:
    type: "select"
    input_style: "choices"
    label: "Funding Scenario"
    description: "Select whether Ryan White funding is briefly interrupted, completely ceases, or interrupted for an extended period"
    show_label: false
    show_description: false
    placeholder: "Select a scenario..."
    value: "cessation"  # Default to cessation scenario
    options:
      brief_interruption:
        id: "brief_interruption"
        label: "Brief Interruption"
        description: "Ryan White funding is briefly interrupted"
      cessation:
        id: "cessation"
        label: "Cessation"
        description: "Ryan White funding completely ceases"
      prolonged_interruption:
        id: "prolonged_interruption"
        label: "Prolonged Interruption"
        description: "Ryan White funding is interrupted for an extended period"

# Simulation file configuration
prerun_simulations:
  provider: "onedrive"  # Options: "local", "onedrive" - change to "onedrive" to use OneDrive
  file_pattern: "prerun/{location}/{scenario}.Rdata"
  config_file: "src/data/providers/onedrive_resources/onedrive_sharing_links.json"  # Path to sharing links file

