# config/pages/prerun.yaml - Pre-run page specific settings
# Updated for Ryan White branch

# Selector configurations
selectors:
  scenario:
    type: "select"
    input_style: "choices"
    label: "Funding Scenario"
    placeholder: "Select a scenario..."
    value: "permanent_loss"  # Default to permanent loss scenario
    options:
      permanent_loss:
        id: "permanent_loss"
        label: "Permanent Funding Loss"
        description: "Ryan White funding is discontinued permanently"
      temporary_loss:
        id: "temporary_loss"
        label: "Temporary Funding Loss"
        description: "Ryan White funding is discontinued but returns in 2029"

# Simulation file configuration
prerun_simulations:
  file_pattern: "prerun/{location}/{scenario}.Rdata"
