# config/pages/prerun.yaml - Pre-run page specific settings
# Simplified version for ryan-white branch

# Selector configurations
selectors:
  scenario:
    type: "select"
    input_style: "choices"
    label: "Scenario"
    placeholder: "Select a scenario..."
    value: "neutral"  # Default to neutral scenario
    options:
      optimistic:
        id: "optimistic"
        label: "Optimistic Scenario"
      neutral:
        id: "neutral"
        label: "Neutral Scenario"
      pessimistic:
        id: "pessimistic"
        label: "Pessimistic Scenario"