# Team page configuration
page:
  title: "Our Team"
  subtitle: "The People Behind the JHEEM Model"
  description: "Meet the researchers and developers working on the JHEEM project"

content:
  members:
    - id: "ddowdy"
      full_name: "David Dowdy, MD, PhD"
      title: "Associate Professor of Epidemiology, International Health, and General Internal Medicine"
      bio: "Dr. David Dowdy, MD, PhD is an Associate Professor of Epidemiology, International Health, and General Internal Medicine at Johns Hopkins. His research interests include epidemiological study of HIV and TB, mechanistic modeling of HIV and TB epidemics, economic evaluation of HIV and TB interventions, and translation of data into appropriate frameworks for decision-making. He sits on the Steering Committee of the TB Modeling and Analysis Consortium, serves as Associate Editor of the International Journal of Tuberculosis and Lung Disease, and is the Principal Investigator of multiple research grants from the National Institutes of Health and other funding agencies to evaluate TB transmission and interventions in the United States, South Africa, Uganda, and Southeast Asia."
      image: "ddowdy.jpg"
    
    - id: "pkasaie"
      full_name: "Parastu Kasaie, MS, PhD"
      title: "Assistant Scientist, Department of Epidemiology"
      bio: "Parastu Kasaie, MS, PhD is an Assistant Scientist in the department of Epidemiology at the Johns Hopkins Bloomberg School of Health. Her research interests lie at the intersection of Operations Research, Epidemiology and Data Sciences. Her methodological expertise is in development and analysis of computer simulation models, and in particular the class of agent-based simulations, for study of disease epidemics in human populations. She has applied these models to study of HIV and TB epidemics, focusing on derivers of transmissions, confection of multiple infectious diseases, and patterns of aging and comorbidities among others. Calibrated against epidemiological data, these simulation models provide a powerful tool to explain the current trends in data, predict future trends under various assumptions and compare the impact of alternative interventions for prevention and control of disease. Dr. Kasaie is currently supported on a K01 career development grant from NIH focusing on studying the epidemic of HIV/AIDS and other Sexually Transmitted Infections among Men who have Sex with Men in Baltimore City."
      image: "pkasaie.jpg"

    - id: "tfojo"
      full_name: "Anthony Fojo, MD, MHS"
      title: "Assistant Professor, Division of General Internal Medicine"
      bio: "Dr. Anthony Fojo, MD, MHS is an Assistant Professor in the Division of General Internal Medicine at the Johns Hopkins School of Medicine. His research centers on improving the individual- and population-level health of persons with HIV using innovative statistical and machine learning algorithms, with a focus on the intersection of HIV and mental health. He has a particular interest in using Bayesian methods and constructing likelihoods to calibrate complex models. Dr. Fojo is currently supported on a K08 award from NIMH focused on the effects of mental health comorbidities on the health of people with HIV and transmission of HIV in the general population."
      image: "tfojo.jpg"

    - id: "mshah"
      full_name: "Maunank Shah, MD, PhD"
      title: "Associate Professor, Infectious Diseases and Epidemiology"
      bio: "Dr. Maunank Shah, MD, PhD is and Associate Professor in Infectious Diseases and Epidemiology at the Johns Hopkins School of Medicine. His research involves the evaluation and application of technologies to improve public health control and clinical care related to infectious diseases, and he has led efforts to develop mathematical transmission models to examine the economic and epidemiological impact of the HIV continuum of care domestically and globally. Additionally, his interests include developing and evaluating the use of mobile health (mHealth) technologies to optimize adherence to medical treatments. Dr. Shah has expertise in decision-analysis, and is the inventor of HIV-ASSIST (www.hivassist.com). HIV-ASSIST offers free, online interactive patient centered decision-support and education for providers choosing ART regimens for people living with HIV. He is Associate Editor for the open source journal for the Infectious Disease Society of America—OFID."
      image: "mshah.jpg"

    - id: "mschnure"
      full_name: "Melissa Schnure"
      title: "PhD Student, Department of Epidemiology"
      bio: "Melissa Schnure is a PhD student in the Department of Epidemiology at the Johns Hopkins Bloomberg School of Public Health. Her current work primarily focuses on modeling the integration of HIV and non-communicable diseases in the sub-Saharan African context. Melissa has previously worked on HIV prevention modeling, specifically for voluntary medical male circumcision and oral pre-exposure prophylaxis. She holds a Master of Science in Infectious Disease Epidemiology from Johns Hopkins Bloomberg School of Public Health and a Bachelor of Arts in Ecology and Evolutionary Biology from Princeton University."
      image: "mschnure.jpg"

    - id: "azalesak"
      full_name: "Andrew Zalesak, MS"
      title: "Research Team Member"
      bio: "Andrew Zalesak, MS, joined the team in March 2023."
      image: "azalesak.png"

layout:
  grid:
    min_width: "300px"
    gap: "2rem"
    columns: "auto-fit" 