# config/components/panels.yaml - Panel component settings
panels:
  base:
    collapsible: true
    defaultVisible: true
    width: 300
  
  left:
    id: "intervention-panel"
    header: "Specify Intervention"
    extends: "base"
    
  right:
    id: "settings-panel"
    header: "Figure Settings"
    extends: "base"