# src/ui/config/visualization.yaml - Visualization settings

# Style manager configuration - controls colors, line types, etc.
style_manager:
  # General style parameters that affect all plots
  general:
    linewidth.slope: 0  # Set line width of slope lines to 0
    alpha.ribbon: 0.2   # Transparency for uncertainty ribbons
  # Styles for baseline vs. intervention comparison
  baseline:
    color: "#0072B2"  # Blue
    alpha: 0.9
  intervention:
    color: "#D55E00"  # Orange (more prominent)
    alpha: 1.0
  # Set to true if you want different line types in addition to colors
  use_different_line_types: false

# Plot appearance customizations - applies to all plots
plot_customizations:
  # Base theme for the plot
  theme_name: "minimal"
  
  # Theme customizations
  theme:
    background_color: "#FFFFFF"
    grid_color: "#E5E5E5"
    text_size: 12
    legend_position: "bottom"
    legend_direction: "horizontal"
  
  # Axis formatting
  axes:
    x_title: "Year"
    y_title: null  # Uses default from plot
    x_format: null  # No special formatting for years
  
  # Facet customization
  facets:
    strip_background: "#F0F0F0"
    strip_text_size: 11

# Baseline simulations configuration
baseline_simulations:
  enabled: true
  # Global settings that apply to both prerun and custom
  default_file_pattern: "base/{location}_base.Rdata"
  
  # Labels for baseline and intervention simulations
  # Labels support template tags like {location} which will be replaced with actual values
  default_label: "Baseline (No Intervention)"
  intervention_label: "Intervention ({location})"
  
  # Page-specific settings
  prerun:
    enabled: true
    # Use provider from page config
    use_provider: true
    # Specify the baseline file pattern (uses default if not specified)
    # file_pattern: "alternate/path/{location}_baseline.Rdata"  # Uncomment to override
    
  custom:
    enabled: true
    # For custom, we can choose to reuse the base simulation
    reuse_base_simset: true
    # Or load a different one if reuse_base_simset is false
    # file_pattern: "special/baseline/{location}.Rdata"  # Uncomment to override
