# src/ui/config/visualization.yaml - Visualization settings

# Baseline simulations configuration
baseline_simulations:
  enabled: true
  # Global settings that apply to both prerun and custom
  default_file_pattern: "base/{location}_base.Rdata"
  
  # Labels for baseline and intervention simulations
  # Labels support template tags like {location} which will be replaced with actual values
  default_label: "Baseline (No Intervention)"
  intervention_label: "Intervention ({location})"
  
  # Visual styling for baseline vs. intervention plots
  plot_styles:
    # General style parameters that affect all plots
    general:
      linewidth.slope: 0  # Set line width of slope lines to 0
      alpha.ribbon: 0.2   # Transparency for uncertainty ribbons
    baseline:
      color: "#0072B2"  # Blue
      alpha: 0.9
    intervention:
      color: "#D55E00"  # Orange (more prominent)
      alpha: 1.0
    # Set to true if you want different line types in addition to colors
    use_different_line_types: false
  
  # Page-specific settings
  prerun:
    enabled: true
    # Use provider from page config
    use_provider: true
    # Specify the baseline file pattern (uses default if not specified)
    # file_pattern: "alternate/path/{location}_baseline.Rdata"  # Uncomment to override
    
  custom:
    enabled: true
    # For custom, we can choose to reuse the base simulation
    reuse_base_simset: true
    # Or load a different one if reuse_base_simset is false
    # file_pattern: "special/baseline/{location}.Rdata"  # Uncomment to override
