# config/base.yaml - Application-wide settings
application:
  name: "JHEEM2"
  version: "2.0.0"
  title: "JHEEM 2 - Ending HIV"
  defaults:
    selected_tab: 'custom_interventions'

theme:
  spacing:
    padding: 15
    headerPadding: "12px 15px"
  transitions:
    duration: 300
  
  # Style and script paths
  styles:
    base: 
      - "css/base/variables.css"
      - "css/main_layout.css"
    layout:
      - "css/layout/three-panel.css"
    components:
      - "css/components/display_panel.css"
      - "css/components/custom_controls.css"
      - "css/components/plot_controls.css"
      - "css/components/plot_panel.css"
      - "css/components/table_panel.css"
      - "css/components/toggle.css"
      - "css/components/accordion.css"
      - "css/components/chevrons.css"
      - "css/components/notifications.css"
      - "css/components/errors.css"
    themes:
      - "css/color_schemes/color_scheme_jh.css"
    pages:
      - "css/pages/prerun.css"
      - "css/pages/custom.css"
      - "css/pages/about.css"
      - "css/pages/overview.css"
      - "css/pages/contact.css" # Grid system CSS
  
  scripts:
    - "js/layout/panel-controls.js"
    - "js/interactions/setup_tooltips.js"

# Page-specific content
pages:
  overview:
    popover:
      title: "Overview"
      content: "Learn about the JHEEM tool and its capabilities"
  faq:
    popover:
      title: "Frequently Asked Questions"
      content: "Find answers to common questions about using JHEEM"
  about:
    popover:
      title: "About JHEEM"
      content: "Learn more about the JHEEM model and its development"
  team:
    popover:
      title: "Our Team"
      content: "Meet the team behind JHEEM's development"
    styles:
      sidebar:
        class: "team_sidebar controls_color"
      main:
        class: "team_main content_color"
      header:
        class: "about_header_padding header_color"
      content:
        class: "about_padding"
  # In base.yaml under pages section
  contact:
    title: "Contact Us"
    description: "We welcome any feedback, comments, questions, or requests"
    form:
      name:
        label: "Your name"
        type: "text"
      email:
        label: "Your email"
        type: "text"
      message:
        label: "Your message"
        placeholder: "Your feedback, comments, questions, or requests"
        height: "250px"
        width: "375px"
    submit:
      label: "Submit"
      class: "cta cta_color"

# Cache configuration
caching:
  cache1:
    max_size: 1000000000  # 1GB
    evict_strategy: "lru"
  cache2:
    max_size: 1000000000  # 1GB
    evict_strategy: "lru"