layout:
  panels:
    left:
      id: "intervention-panel"
      width: 300
      header: "Select Intervention"
      collapsible: true
      defaultVisible: true
    right:
      id: "settings-panel"
      width: 300
      header: "Figure Settings"
      collapsible: true
      defaultVisible: true
  
  transitions:
    duration: 300
    
  styles:
    colors:
      border: "#ddd"
      header: "#f8f9fa"
      panel: "#fff"
    spacing:
      padding: 15
      headerPadding: "12px 15px"