# src/ui/config/defaults.yaml
# Default configurations used across the application

# Core application-wide defaults and shared configurations
defaults:
  panel:
    width: 300
    collapsible: true
    defaultVisible: true
  display:
    plot:
      height: "600px"
      defaultType: "static"
  buttons:
    generate:
      label: "Generate Projections"
      primary_class: "btn-primary"
  feedback:
    generate:
      message: "This will take 10-30 seconds"
      show_chime: true
      chime_label: "Play a chime when done"

# Display settings
display:
  plot:
    height: "600px"
    defaultType: "static"
    container_class: "plot-container"
  loading:
    message: "Generating plot..."
    class: "loading-indicator"

# Section configurations
sections:
  location:
    title: "Location"
    description: "Select the geographic area for the model"
  scenario:
    title: "Funding Scenario"
    description: "Choose whether Ryan White funding is permanently discontinued or temporarily suspended"

# Panel configurations
panels:
  left:
    id: "intervention-panel"
    header: "Ryan White Funding Impact"
    description: "Explore the impact of changes to Ryan White program funding on HIV transmission and viral suppression."
    width: 300
    collapsible: true
    defaultVisible: true
  right:
    id: "settings-panel"
    header: "Figure Settings"
    description: "Customize how the results are displayed."
    width: 300
    collapsible: true
    defaultVisible: true

# Input type defaults - used across all pages
input_types:
  select:
    default_style: "choices"
    multiple: false
  radio:
    default_style: "native"
    multiple: false
  checkbox:
    default_style: "native"
    multiple: true
  numeric:
    default_style: "native"
    multiple: false

# Common selectors used across multiple pages
selectors:
  location:
    type: "select"
    label: "Location"
    description: "Select the geographic area for the model"
    show_label: true
    placeholder: "Select a location..."
    value: "C.33100"  # Default to Miami
    options:
      atlanta:
        id: "C.12580"
        label: "Atlanta-Sandy Springs-Roswell, GA"
      miami:
        id: "C.33100"
        label: "Miami-Fort Lauderdale-Pompano Beach, FL"
      chicago:
        id: "C.16980"
        label: "Chicago-Naperville-Elgin, IL-IN-WI"

# Model dimension mappings - used for translating UI to model values
model_dimensions:
  age:
    ui_field: "age_groups"
    mappings:
      "13-24": "13-24 years"
      "25-34": "25-34 years"
      "35-44": "35-44 years"
      "45-54": "45-54 years"
      "55plus": "55+ years"
  
  sex:
    ui_field: "biological_sex"
    mappings:
      "heterosexual_male": "heterosexual_male"
      "msm": "msm"
      "female": "female"
  
  risk:
    ui_field: "risk_factor"
    mappings:
      "never_IDU": "never_IDU"
      "active_IDU": "active_IDU"
      "IDU_in_remission": "IDU_in_remission"
  
  race:
    ui_field: "race_ethnicity"
    mappings:
      "black": "black"
      "hispanic": "hispanic"
      "other": "other"

# Testing mode configuration
testing:
  enabled: true  # Set to true for test mode
  simulations:
    prerun:
      file: "test/prerun/C.12580_test_all_2024_2025_moderate.Rdata"
    custom:
      file: "test/custom/C.12580_base_test.Rdata"

